FROM golang:1.18 as builder

WORKDIR /plugin-dev

# Install Delve for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ENV GO111MODULE on
ENV DEBUG true

# Symlink tls folder to the expected path
RUN ln -s "$(pwd)/tls" /tls

ENTRYPOINT ["sleep", "999999999999"]