FROM golang:1.18 as builder

WORKDIR /plugin-dev

# Install Delve for debugging
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ENV GO111MODULE on
ENV DEBUG true

# Symlink manifests and tls folders to the expected paths
RUN ln -s "$(pwd)/manifests" /manifests
RUN ln -s "$(pwd)/tls" /tls

ENTRYPOINT ["sleep", "999999999999"]